queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Misc tests (checks)
      # - status-success=Misc tests (licenses)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Unit tests (py310-unittest)
      - status-success=Unit tests (py311-unittest)
      - status-success=Unit tests (py312-unittest)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)
      - status-success=Integration tests (3.10)
      - status-success=Integration tests (3.11)
      - status-success=Integration tests (3.12)


pull_request_rules:

  - name: default
    actions:
      queue:
        name: default
        method: rebase
    conditions:
      - label!=no-mergify
      - -draft
      - approved-reviews-by=@fedora-infra/fedora-messaging-maintainers
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Misc tests (checks)
      # - status-success=Misc tests (licenses)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Unit tests (py310-unittest)
      - status-success=Unit tests (py311-unittest)
      - status-success=Unit tests (py312-unittest)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)
      - status-success=Integration tests (3.10)
      - status-success=Integration tests (3.11)
      - status-success=Integration tests (3.12)

  # Merge contributions from the team as long as they have one approval by anyone
  - name: default-from-fedora-messaging-team
    actions:
      queue:
        name: default
        method: rebase
    conditions:
      - label!=no-mergify
      - -draft
      - author=@fedora-infra/fedora-messaging-maintainers
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Misc tests (checks)
      # - status-success=Misc tests (licenses)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Unit tests (py310-unittest)
      - status-success=Unit tests (py311-unittest)
      - status-success=Unit tests (py312-unittest)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)
      - status-success=Integration tests (3.10)
      - status-success=Integration tests (3.11)
      - status-success=Integration tests (3.12)
